import { PostListItem } from "@types";
export const MOCK_NOTICE_LIST: PostListItem[] = [
  {
    postId: 17,
    title:
      "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 13:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: true,
    commentsSize: 123,
    pined: true,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 16,
    title:
      "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 13:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: false,
    commentsSize: 123,
    pined: true,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 15,
    title: "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: true,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 14,
    title: "공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "테크모",
    },
    views: 12,
    hasAttachment: false,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 13,
    title: "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: true,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 12,
    title: "공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "테크모",
    },
    views: 12,
    hasAttachment: false,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 11,
    title: "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: true,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 10,
    title: "공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "테크모",
    },
    views: 12,
    hasAttachment: false,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 9,
    title: "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: true,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 8,
    title: "공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "테크모",
    },
    views: 12,
    hasAttachment: false,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 7,
    title: "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: true,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 6,
    title: "공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "테크모",
    },
    views: 12,
    hasAttachment: false,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 5,
    title: "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: true,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 4,
    title: "공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "테크모",
    },
    views: 12,
    hasAttachment: false,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 3,
    title: "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: true,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 2,
    title: "공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "테크모",
    },
    views: 12,
    hasAttachment: false,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 1,
    title: "공지사항 제목입니다. 공지사항 제목입니다. 공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "닉넴최대여덟글자",
    },
    views: 12,
    hasAttachment: true,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
  {
    postId: 0,
    title: "공지사항 제목입니다.",
    createdDateTime: "2021-08-01 12:00:00",
    modifiedDateTime: "2021-08-01 12:00:00",
    author: {
      loginId: "anonymous",
      name: "테크모",
    },
    views: 12,
    hasAttachment: false,
    commentsSize: 32,
    pined: false,
    category: {
      mainCategory: "공지사항",
      subCategory: "공지공지",
    },
  },
];
